import { Metadata } from "next";
import { Send, MessageSquare, Star, Bell, BarChart3, Shield } from "lucide-react";
import { ServicePage } from "@/components/templates/service-page";

export const metadata: Metadata = {
  title: "Review Management & Reputation Automation",
  description:
    "Get 5-star reviews on autopilot. Automated review requests, AI-powered responses, and reputation monitoring for local businesses. Starting at $97/month.",
  openGraph: {
    title: "Review Management & Reputation Automation | SignalCrew",
    description:
      "Get 5-star reviews on autopilot. Automated review requests and reputation monitoring. Starting at $97/month.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Review Management & Reputation Automation | SignalCrew",
    description:
      "Get 5-star reviews on autopilot. Automated review requests and reputation monitoring. Starting at $97/month.",
  },
};

export default function ReviewManagementPage() {
  return (
    <ServicePage
      hero={{
        title:
          "Your best customers forget to leave reviews. Your worst ones don\u2019t.",
        description:
          "Automated review requests from happy customers. Private routing for unhappy ones. Your reputation builds itself.",
        ctaText: "Boost My Reviews",
        ctaHref: "/contact",
        secondaryCtaText: "View Pricing",
        secondaryCtaHref: "/pricing",
      }}
      problem={{
        title: "Happy customers stay silent. Angry ones shout.",
        paragraphs: [
          "You do great work. Your customers tell you so in person. But when it comes to actually leaving a review? They mean to. They just never get around to it. Meanwhile, the one customer who had a bad day can&apos;t wait to share.",
          "<strong class=\"text-ink-900\">88% of consumers trust online reviews as much as personal recommendations.</strong> Your review profile is often the very first impression potential customers get of your business.",
          "Responding to every review -- especially negative ones -- takes time you don&apos;t have. But unanswered reviews signal that you <span class=\"font-display font-bold text-signal-orange\">don&apos;t care</span>.",
        ],
      }}
      features={{
        title: "Complete reputation management.",
        subtitle:
          "From review requests to responses, your entire review workflow -- automated.",
        items: [
          {
            icon: Send,
            title: "Automated Review Requests",
            description:
              "SMS and email review requests sent automatically after every job. Timing is optimized for maximum response rate.",
          },
          {
            icon: MessageSquare,
            title: "AI-Powered Review Responses",
            description:
              "Professional responses to every review -- positive or negative -- generated by AI and customized for your brand voice.",
          },
          {
            icon: Star,
            title: "Multi-Platform Support",
            description:
              "Manage reviews across Google, Yelp, Facebook, and industry-specific platforms from one dashboard.",
          },
          {
            icon: Bell,
            title: "Reputation Monitoring Alerts",
            description:
              "Instant notifications for new reviews so you can address issues quickly and celebrate wins with your team.",
          },
          {
            icon: BarChart3,
            title: "Review Analytics Dashboard",
            description:
              "Track review velocity, sentiment trends, and star rating changes over time with clear, actionable visualizations.",
          },
          {
            icon: Shield,
            title: "Negative Review Interception",
            description:
              "Unhappy customers get routed to private feedback first, giving you a chance to make it right before they post publicly.",
          },
        ],
      }}
      useCases={{
        title: "How it works in practice.",
        subtitle:
          "Real scenarios showing the power of automated reputation management.",
        items: [
          {
            title: "Post-Job Review Automation",
            description:
              "Customer pays their invoice. Two hours later, they receive a friendly text with a direct link to leave a review. No manual effort. No forgetting. Every job becomes a review opportunity.",
          },
          {
            title: "Negative Review Recovery",
            description:
              "A 2-star review comes in. You're notified instantly. AI drafts a professional, empathetic response. You reply within minutes -- showing every future customer that you care.",
          },
          {
            title: "Review Velocity Boost",
            description:
              "Going from 2 reviews per month to 10+ reviews per month doesn't just look good -- it dramatically improves your Google ranking and local search visibility.",
          },
          {
            title: "Competitive Differentiation",
            description:
              "When prospects compare your 4.8-star rating with 200 reviews against a competitor's 3.9 with 30 reviews, the decision makes itself. Reviews are your best sales tool.",
          },
        ],
      }}
      stats={[
        { stat: "88%", label: "Trust online reviews like personal recommendations" },
        { stat: "5x", label: "More reviews with automated requests" },
        { stat: "94%", label: "Say reviews influenced their buying decision" },
      ]}
      pricing={{
        label: "Start building your reputation.",
        price: "$97",
        suffix: "/mo",
        subtitle:
          "Review Management starts at just $97/month. The cost of one unanswered negative review is far higher.",
        ctaText: "Get Started",
        ctaHref: "/contact",
        bullets: [
          "Unlimited review requests",
          "AI-generated responses",
          "Multi-platform support",
        ],
      }}
    />
  );
}
