import { Metadata } from "next";
import Link from "next/link";
import {
  Star,
  Send,
  MessageSquare,
  Bell,
  BarChart3,
  Shield,
  ArrowRight,
  Check,
  ThumbsDown,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Review Management & Reputation Automation",
  description:
    "Get 5-star reviews on autopilot. Automated review requests, AI-powered responses, and reputation monitoring for local businesses. Starting at $97/month.",
};

const features = [
  {
    icon: Send,
    title: "Automated Review Requests",
    description:
      "Automatically send review requests via SMS and email after every job. Timing is optimized for maximum response.",
  },
  {
    icon: MessageSquare,
    title: "AI-Powered Review Responses",
    description:
      "Professional responses to every review—positive or negative—generated by AI and customized for your brand.",
  },
  {
    icon: Star,
    title: "Multi-Platform Support",
    description:
      "Manage reviews across Google, Yelp, Facebook, and industry-specific platforms from one dashboard.",
  },
  {
    icon: Bell,
    title: "Reputation Monitoring Alerts",
    description:
      "Instant notifications for new reviews so you can address issues quickly and celebrate wins.",
  },
  {
    icon: BarChart3,
    title: "Review Analytics Dashboard",
    description:
      "Track review velocity, sentiment trends, and star rating changes over time with clear visualizations.",
  },
  {
    icon: Shield,
    title: "Negative Review Interception",
    description:
      "Unhappy customers are routed to private feedback before posting publicly, giving you a chance to make it right.",
  },
];

const useCases = [
  {
    title: "Post-Job Review Automation",
    description:
      "Customer pays their invoice. 2 hours later, they receive a friendly text asking about their experience with a direct link to leave a review.",
  },
  {
    title: "Negative Review Recovery",
    description:
      "A 2-star review comes in. You're notified instantly, AI drafts a professional response, and you can reply within minutes to show you care.",
  },
  {
    title: "Review Velocity Boost",
    description:
      "Going from 2 reviews per month to 10+ reviews per month dramatically improves your Google ranking and visibility.",
  },
  {
    title: "Competitive Differentiation",
    description:
      "When prospects compare your 4.8-star rating with 200 reviews against a competitor's 3.9 with 30 reviews, you win.",
  },
];

export default function ReviewManagementPage() {
  return (
    <>
      {/* Hero */}
      <section className="bg-navy-900 py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <div className="inline-flex items-center gap-2 rounded-full bg-navy-800 px-4 py-2 text-sm text-navy-300">
              <Star className="h-4 w-4 text-cta-400" />
              Review Management
            </div>
            <h1 className="mt-6 text-4xl font-bold tracking-tight text-white sm:text-5xl">
              5-Star Reviews on Autopilot
            </h1>
            <p className="mt-6 text-lg text-navy-300">
              Automatically request reviews from happy customers and respond to all reviews
              professionally. Build the reputation your business deserves.
            </p>
            <div className="mt-10 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Button
                asChild
                size="lg"
                className="w-full sm:w-auto bg-cta-500 hover:bg-cta-600 text-white font-semibold px-8"
              >
                <Link href="/contact">
                  Boost My Reviews
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
              <Button
                asChild
                variant="outline"
                size="lg"
                className="w-full sm:w-auto border-navy-600 text-white hover:bg-navy-800"
              >
                <Link href="/pricing">View Pricing</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Problem */}
      <section className="bg-background py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl">
            <div className="flex items-center gap-3">
              <ThumbsDown className="h-8 w-8 text-red-500" />
              <h2 className="text-3xl font-bold text-navy-900">The Problem</h2>
            </div>
            <div className="mt-8 space-y-6 text-lg text-navy-600">
              <p>
                Happy customers rarely leave reviews on their own. But upset customers?
                They can't wait to share their experience. This creates a review profile
                that doesn't reflect the quality of your work.
              </p>
              <p>
                <strong className="text-navy-900">
                  88% of consumers trust online reviews as much as personal recommendations.
                </strong>{" "}
                Your review profile is often the first impression potential customers get.
              </p>
              <p>
                Meanwhile, responding to every review—especially negative ones—takes time
                you don't have. But unanswered reviews signal that you don't care about
                customer feedback.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-navy-50 py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold text-navy-900">
              Complete Reputation Management
            </h2>
            <p className="mt-4 text-lg text-navy-600">
              From requests to responses, we automate your entire review workflow.
            </p>
          </div>

          <div className="mt-16 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.title} className="rounded-xl bg-white p-6 shadow-sm">
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-cta-100">
                  <feature.icon className="h-6 w-6 text-cta-600" />
                </div>
                <h3 className="mt-4 text-lg font-semibold text-navy-900">
                  {feature.title}
                </h3>
                <p className="mt-2 text-navy-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="bg-background py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold text-navy-900">How It Works in Practice</h2>
            <p className="mt-4 text-lg text-navy-600">
              Real scenarios showing the power of automated reputation management.
            </p>
          </div>

          <div className="mt-16 grid grid-cols-1 gap-8 sm:grid-cols-2">
            {useCases.map((useCase) => (
              <div
                key={useCase.title}
                className="rounded-xl border border-navy-200 bg-white p-8"
              >
                <h3 className="text-xl font-semibold text-navy-900">{useCase.title}</h3>
                <p className="mt-4 text-navy-600">{useCase.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="bg-navy-900 py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold text-white">The Impact of Reviews</h2>
          </div>
          <div className="mt-12 grid grid-cols-1 gap-8 sm:grid-cols-3">
            <div className="text-center">
              <p className="text-5xl font-bold text-cta-400">88%</p>
              <p className="mt-2 text-navy-300">Trust online reviews like recommendations</p>
            </div>
            <div className="text-center">
              <p className="text-5xl font-bold text-cta-400">5x</p>
              <p className="mt-2 text-navy-300">More reviews with automated requests</p>
            </div>
            <div className="text-center">
              <p className="text-5xl font-bold text-cta-400">94%</p>
              <p className="mt-2 text-navy-300">Say reviews influenced their decision</p>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Preview */}
      <section className="bg-background py-16 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="rounded-2xl border border-navy-200 bg-white p-8 sm:p-12">
            <div className="grid grid-cols-1 gap-8 lg:grid-cols-2 lg:items-center">
              <div>
                <h2 className="text-3xl font-bold text-navy-900">
                  Start Building Your Reputation
                </h2>
                <p className="mt-4 text-lg text-navy-600">
                  Review Management starts at just $97/month. The cost of one negative
                  review going unanswered is far higher.
                </p>
                <ul className="mt-6 space-y-3">
                  <li className="flex items-center gap-3 text-navy-700">
                    <Check className="h-5 w-5 text-success-600" />
                    Unlimited review requests
                  </li>
                  <li className="flex items-center gap-3 text-navy-700">
                    <Check className="h-5 w-5 text-success-600" />
                    AI-generated responses
                  </li>
                  <li className="flex items-center gap-3 text-navy-700">
                    <Check className="h-5 w-5 text-success-600" />
                    Multi-platform support
                  </li>
                </ul>
              </div>
              <div className="text-center lg:text-right">
                <p className="text-sm text-navy-500">Starting at</p>
                <p className="text-5xl font-bold text-navy-900">
                  $97<span className="text-xl font-normal text-navy-500">/mo</span>
                </p>
                <Button
                  asChild
                  size="lg"
                  className="mt-6 bg-cta-500 hover:bg-cta-600 text-white font-semibold px-8"
                >
                  <Link href="/contact">
                    Get Started
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
